# Site settings
year: 2018
name: ASU CIS
title: CIS Home
description: Awesome description
url: https://asucis.com
baseurl: ""
email: international.students@asu.edu
cover: 
logo: assets/images/favicon.png

# Build settings
markdown: redcarpet
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]